ERROR:root:An error occurred: name 'model' is not defined
ERROR:root:An error occurred: segment_everything() got an unexpected keyword argument 'model'
ERROR:root:An error occurred: segment_everything() got an unexpected keyword argument 'model'
ERROR:root:An error occurred: segment_everything() got an unexpected keyword argument 'model'
ERROR:root:An error occurred: segment_everything() got an unexpected keyword argument 'model'
ERROR:root:An error occurred: segment_everything() got an unexpected keyword argument 'model'
ERROR:root:An error occurred: segment_everything() got an unexpected keyword argument 'model'
ERROR:root:An error occurred: Cannot hash argument 'model' (of type `ultralytics.models.yolo.model.YOLO`) in 'segment_everything'.

To address this, you can tell Streamlit not to hash this argument by adding a
leading underscore to the argument's name in the function signature:

```
@st.cache_data
def segment_everything(_model, ...):
    ...
```
            
ERROR:root:An error occurred: Cannot hash argument 'model' (of type `ultralytics.models.yolo.model.YOLO`) in 'segment_everything'.

To address this, you can tell Streamlit not to hash this argument by adding a
leading underscore to the argument's name in the function signature:

```
@st.cache_resource
def segment_everything(_model, ...):
    ...
```
            
ERROR:root:An error occurred: Cannot hash argument 'annotations' (of type `torch.Tensor`) in 'fast_process'.

To address this, you can tell Streamlit not to hash this argument by adding a
leading underscore to the argument's name in the function signature:

```
@st.cache_resource
def fast_process(_annotations, ...):
    ...
```
            
ERROR:root:An error occurred: tuple index out of range
ERROR:root:An error occurred: drawable_canvas() missing 2 required positional arguments: 'annotations' and 'update_segmentation_results'
ERROR:root:An error occurred: tuple index out of range
ERROR:root:An error occurred: tuple index out of range
ERROR:root:An error occurred: tuple index out of range
ERROR:root:An error occurred: cannot unpack non-iterable int object
ERROR:root:An error occurred: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 8791780800 bytes.
ERROR:root:An error occurred: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 23004463104 bytes.
ERROR:root:An error occurred: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 4685345280 bytes.
ERROR:root:An error occurred: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 7493472768 bytes.
ERROR:root:An error occurred: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 8282112000 bytes.
ERROR:root:An error occurred: tuple index out of range
ERROR:root:An error occurred: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 12423168000 bytes.
ERROR:root:An error occurred: tuple index out of range
ERROR:root:An error occurred: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 15366574080 bytes.
ERROR:root:An error occurred: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 10655563776 bytes.
ERROR:root:An error occurred: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 22683435008 bytes.
ERROR:root:An error occurred: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 5753401600 bytes.
ERROR:root:An error occurred: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 20216166400 bytes.
ERROR:root:An error occurred: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 4364006400 bytes.
ERROR:root:An error occurred: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 15180774400 bytes.
ERROR:root:An error occurred: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 25800000000 bytes.
ERROR:root:An error occurred: Cannot hash argument 'annotations' (of type `torch.Tensor`) in 'calculate_parameters'.

To address this, you can tell Streamlit not to hash this argument by adding a
leading underscore to the argument's name in the function signature:

```
@st.cache_data
def calculate_parameters(_annotations, ...):
    ...
```
            
ERROR:root:An error occurred: Cannot hash argument 'annotations' (of type `torch.Tensor`) in 'calculate_parameters'.

To address this, you can tell Streamlit not to hash this argument by adding a
leading underscore to the argument's name in the function signature:

```
@st.cache_resource
def calculate_parameters(_annotations, ...):
    ...
```
            
ERROR:root:An error occurred: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

ERROR:root:An error occurred: st_canvas() got an unexpected keyword argument 'background_image_aspect_ratio'
ERROR:root:An error occurred: Cannot hash argument 'annotations' (of type `torch.Tensor`) in 'calculate_parameters'.

To address this, you can tell Streamlit not to hash this argument by adding a
leading underscore to the argument's name in the function signature:

```
@st.cache_data
def calculate_parameters(_annotations, ...):
    ...
```
            
ERROR:root:An error occurred: name 'device' is not defined
ERROR:root:An error occurred: name 'device' is not defined
ERROR:root:An error occurred: 'numpy.ndarray' object has no attribute 'cpu'
ERROR:root:An error occurred: 'numpy.ndarray' object has no attribute 'cpu'
ERROR:root:An error occurred: 'numpy.ndarray' object has no attribute 'cpu'
ERROR:root:An error occurred: 'numpy.ndarray' object has no attribute 'cpu'
ERROR:root:An error occurred: 'numpy.ndarray' object has no attribute 'numpy'
ERROR:root:An error occurred: 'numpy.ndarray' object has no attribute 'cpu'
ERROR:root:An error occurred: Cannot hash argument 'annotations' (of type `torch.Tensor`) in 'calculate_parameters'.

To address this, you can tell Streamlit not to hash this argument by adding a
leading underscore to the argument's name in the function signature:

```
@st.cache_data
def calculate_parameters(_annotations, ...):
    ...
```
            
ERROR:root:An error occurred: Cannot hash argument 'annotations' (of type `torch.Tensor`) in 'calculate_parameters'.

To address this, you can tell Streamlit not to hash this argument by adding a
leading underscore to the argument's name in the function signature:

```
@st.cache_data
def calculate_parameters(_annotations, ...):
    ...
```
            
ERROR:root:An error occurred: Cannot hash argument 'model' (of type `ultralytics.yolo.engine.model.YOLO`) in 'segment_everything'.

To address this, you can tell Streamlit not to hash this argument by adding a
leading underscore to the argument's name in the function signature:

```
@st.cache_data
def segment_everything(_model, ...):
    ...
```
            
ERROR:root:An error occurred: Cannot hash argument 'model' (of type `ultralytics.yolo.engine.model.YOLO`) in 'segment_everything'.

To address this, you can tell Streamlit not to hash this argument by adding a
leading underscore to the argument's name in the function signature:

```
@st.cache_data
def segment_everything(_model, ...):
    ...
```
            
ERROR:root:An error occurred: [enforce fail at alloc_cpu.cpp:114] data. DefaultCPUAllocator: not enough memory: you tried to allocate 27472896000 bytes.
ERROR:root:An error occurred: [enforce fail at alloc_cpu.cpp:114] data. DefaultCPUAllocator: not enough memory: you tried to allocate 27472896000 bytes.
ERROR:root:An error occurred: cannot unpack non-iterable int object
ERROR:root:An error occurred: cannot unpack non-iterable int object
ERROR:root:An error occurred: cannot unpack non-iterable int object
ERROR:root:An error occurred: cannot unpack non-iterable int object
ERROR:root:An error occurred: cannot unpack non-iterable int object
ERROR:root:An error occurred: cannot unpack non-iterable int object
ERROR:root:An error occurred: cannot unpack non-iterable int object
ERROR:root:An error occurred: local variable 'segmented_image' referenced before assignment
ERROR:root:An error occurred: local variable 'segmented_image' referenced before assignment
ERROR:root:An error occurred: local variable 'segmented_image' referenced before assignment
ERROR:root:An error occurred: local variable 'segmented_image' referenced before assignment
ERROR:root:An error occurred: local variable 'segmented_image' referenced before assignment
ERROR:root:An error occurred: drawable_canvas() missing 1 required positional argument: 'input_size'
ERROR:root:An error occurred: drawable_canvas() missing 1 required positional argument: 'input_size'
ERROR:root:An error occurred: local variable 'pixel_length' referenced before assignment
ERROR:root:An error occurred: Boolean value of Tensor with more than one value is ambiguous
ERROR:root:An error occurred: float division by zero
ERROR:root:An error occurred: float division by zero
ERROR:root:An error occurred: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
ERROR:root:An error occurred: local variable 'feret_diameter_micron' referenced before assignment
ERROR:root:An error occurred: name 'min_feret_diameter_micron' is not defined
ERROR:root:An error occurred: [enforce fail at alloc_cpu.cpp:114] data. DefaultCPUAllocator: not enough memory: you tried to allocate 29915208704 bytes.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-25015' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at c:\Users\fares\Documents\interpreterwithgemini\test_gemini\lib\site-packages\tornado\websocket.py:1090> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "c:\Users\fares\Documents\interpreterwithgemini\test_gemini\lib\site-packages\tornado\websocket.py", line 1092, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\fares\Documents\interpreterwithgemini\test_gemini\lib\site-packages\tornado\websocket.py", line 1094, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
ERROR:root:An error occurred: [enforce fail at alloc_cpu.cpp:114] data. DefaultCPUAllocator: not enough memory: you tried to allocate 16398000000 bytes.
ERROR:root:An error occurred: [enforce fail at alloc_cpu.cpp:114] data. DefaultCPUAllocator: not enough memory: you tried to allocate 39407287296 bytes.
